services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JsonFormBuilderBundle\Service\FormFieldTypeFactory: ~
    JsonFormBuilderBundle\Service\FormTextElementTypeFactory: ~
